-- Stable, human-readable identifiers allow moderators to manage quotes in chat.
alter table public.community_quotes
  add column if not exists quote_number bigint generated by default as identity;

create unique index if not exists community_quotes_quote_number_idx
  on public.community_quotes(quote_number);

alter table public.community_quotes
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists last_edited_by text,
  add column if not exists last_edited_platform text;

-- Keep the three original examples in the public archive. The NOT EXISTS
-- checks make this safe to run even when an older seed already created them.
insert into public.community_quotes
  (quote_text,author_name,platform,quoted_at,approved,status,submitted_by,bot_announced_at,bot_queued_at)
select
  seed.quote_text,seed.author_name,seed.platform,seed.quoted_at,true,'approved',seed.submitted_by,now(),now()
from (values
  ('Eu vim pela gameplay. Fiquei pelo desastre.','gabi.exe','TWITCH','2026-08-09 18:00:00-03'::timestamptz,'THENEES'),
  ('Tecnicamente não perdemos. Só paramos de ganhar.','pixelmago','KICK','2026-08-02 18:00:00-03'::timestamptz,'MODERAÇÃO'),
  ('O plano funcionou até a parte em que começou.','luquinhas_77','TWITCH','2026-07-27 18:00:00-03'::timestamptz,'THENEES')
) as seed(quote_text,author_name,platform,quoted_at,submitted_by)
where not exists (
  select 1 from public.community_quotes existing
  where lower(existing.quote_text)=lower(seed.quote_text)
);

insert into public.bot_commands(command,description,response_template,permission,cooldown_seconds,enabled,sort_order)
values
  ('!editquote','Edita uma quote pelo número. Uso: !editquote número nova frase','Use !editquote número nova frase.','moderator',3,true,20),
  ('!delquote','Exclui uma quote pelo número. Uso: !delquote número','Use !delquote número.','moderator',3,true,21)
on conflict(command) do update set
  description=excluded.description,
  response_template=excluded.response_template,
  permission='moderator',
  cooldown_seconds=excluded.cooldown_seconds;
